name: Deploy sample to existing Scaleway Serverless Container
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to Scaleway Container Registry
    runs-on: ubuntu-latest
    env:
      SCALEWAY_REGION: fr-par
      SCALEWAY_REGISTRY_NAMESPACE_ID: bebe6b50-0783-4a48-9256-2d0c161c3cbf
      SCALEWAY_SERVERLESS_CONTAINER_NAME: samplecontainer
      SCALEWAY_SERVERLESS_NAMESPACE_ID: 29841af4-b17e-4443-8abc-7811a1158a60
      SCALEWAY_SERVERLESS_CONTAINER_ID: ed088303-b24c-4e6b-a935-4a1c0c22cd25
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get Scaleway Container Registry endpoint
        id: get_registry_endpoint
        uses: fjogeleit/http-request-action@master
        with:
          url: https://api.scaleway.com/registry/v1/regions/${{env.SCALEWAY_REGION}}/namespaces/${{env.SCALEWAY_REGISTRY_NAMESPACE_ID}}
          method: GET
          customHeaders: '{"X-Auth-Token":"${{secrets.SCALEWAY_API_TOKEN}}"}'
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{fromJSON(steps.get_registry_endpoint.outputs.response).endpoint}}
          username: not_used
          password: ${{secrets.SCALEWAY_API_TOKEN}}
      - name: Build image and push it to the Scaleway Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./sample
          push: true
          tags: ${{fromJSON(steps.get_registry_endpoint.outputs.response).endpoint}}/${{env.SCALEWAY_SERVERLESS_CONTAINER_NAME}}:latest
      - name: Deploy image to Scaleway Serverless Container
        uses: fjogeleit/http-request-action@master
        with:
          url: https://api.scaleway.com/functions/v1alpha2/regions/${{env.SCALEWAY_REGION}}/containers/${{env.SCALEWAY_SERVERLESS_CONTAINER_ID}}/deploy
          method: POST
          customHeaders: '{"X-Auth-Token":"${{secrets.SCALEWAY_API_TOKEN}}"}'

